## Exercise 1 - Create a new 3x2 matrix. Extract 2 values via indexing.

    [[1402,191],
     [1371,821],
     [949,1437]]
     

In [19]:
import numpy as np

# matrix creation
mat = np.matrix([[1402, 191],[1371, 821],[949, 1437]])

# slicing like a pandas df, need to look into if there is a better way of doing this, I suspect that there is
print(mat[2:,:1])
print(mat[2:,1:])

[[949]]
[[1437]]


## Exercise 2 - Add, Subtract, Multiply and Divide 2 Matrices

    [[0, 4],
     [2, 0]]

    [[-1, 2],
     [1, -2]]

In [7]:
A = np.matrix([[0, 4],[2, 0]])
B = np.matrix([[-1,2],[1,-2]])

# standard operations
print(A+B,'\n')
print(A-B,'\n')

# I read that multiplication requires the dot function, but if I just use *, I get the same result. Unsure why
print(np.dot(A,B),'\n')
print(A/B,'\n')

[[-1  6]
 [ 3 -2]] 

[[1 2]
 [1 2]] 

[[ 4 -8]
 [-2  4]] 

[[-0.  2.]
 [ 2. -0.]] 



## Exercise 3 - Create a 3x3 Identity Matrix. Show that for any matrix A, AI=IA=A.

    [[4,2,1],
     [4,8,3],
     [1,1,0]]

In [9]:
import numpy.linalg

# I believe there is a function specifically for this
iden = np.matrix([[1,0,0],[0,1,0],[0,0,1]])


A = np.matrix([[4,2,1],[4,8,3],[1,1,0]])

print("AI: \n{}".format(A*iden))
print("IA: \n{}".format(iden*A))
print("A: \n{}".format(A))

AI: 
[[4 2 1]
 [4 8 3]
 [1 1 0]]
IA: 
[[4 2 1]
 [4 8 3]
 [1 1 0]]
A: 
[[4 2 1]
 [4 8 3]
 [1 1 0]]


## Exercise 4 - Transpose a Matrix. What do we need to pivot a matrix?

    [[0 1]
     [2 3]
     [4 5]]

In [20]:
A = np.matrix([[0,1],[2,3],[4,5]])

print(A.transpose())

[[0 2 4]
 [1 3 5]]


As far as I can tell, you can always transpose a matrix, so I don't really understand the question

## Exercise 5 - Invert a Matrix. What happens when a matrix is not invertible?

    [[1, 4],
     [2, 0]]

In [21]:
A = np.matrix([[1,4],[2,0]])

print(np.linalg.inv(A))

[[ 0.     0.5  ]
 [ 0.25  -0.125]]


The matrix is singular if it cannot be inverted

## Exercise 6 - Find the determinant for the following 3 matrices.

        [[1, 2], 
         [3, 4]], 
        
        [[1, 2], 
         [2, 1]],
        
        [[1, 3],
         [3, 1]]

In [24]:
A = np.matrix([[1,2],[3,4]])

B = np.matrix([[1,2],[2,1]])

C = np.matrix([[1,3],[3,1]])

print(np.linalg.det(A), '\n')
print(np.linalg.det(B), '\n')
print(np.linalg.det(C))

-2.0 

-3.0 

-8.0


## Exercise 6 - Solve the following linear system.

- 3x + y = 9
- x + 2y = 8

y = 3x - 9
x + 2(3x - 9) = 8
7x - 18 = 8
x = -1.428
3(-1.428) + y = 9
y = 13.286

## Exercise 7 - Compute the eigenvalues and eigenvectors for the following matrix. What do these represent?

    [[1, 2, 1],
     [6, -1, 0],
     [-1, -2, -1]]

In [29]:
A = np.matrix([[1,2,1],[6,-1,0],[-1,-2,-1]])

# eig returns eigenvalues, then eigenvectors
vals, vect = np.linalg.eig(A)
print("Eigenvalues:\n{}".format(vals))
print('Eigenvector:\n{}'.format(vect))

Eigenvalues:
[ -4.00000000e+00   3.00000000e+00   1.71642331e-16]
Eigenvector:
[[ 0.40824829 -0.48507125 -0.0696733 ]
 [-0.81649658 -0.72760688 -0.41803981]
 [-0.40824829  0.48507125  0.90575292]]


An eigenvector of a matrix is a non-zero vector that, when a scalar eigenvalue is applied to it, is the same direction as the original matrix. 